[package]
name = "tcp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
