[package]
name = "tcp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest-wasm = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"

[lib]
name = "client"
path = "src/main.rs"
